hyperledger/aries-framework-go-ext

.github/workflows/common.yml, .github/workflows/license.yml, .github/workflows/storage-couchdb.yml, .github/workflows/storage-mysql.yml, .gitignore, .golangci.yml, Makefile, component/storage/couchdb/go.mod, component/storage/mysql/go.mod, go.mod, scripts/check_license.sh, scripts/check_lint.sh, scripts/check_unit.sh
This PR includes:
* global checks for Apache v2 License headers
* global checks for unit tests
* global linter
=> feat: Adds global checks

.codecov.yaml, .github/workflows/common.yml
This PR includes:
* adds codecov.yaml file
* prevents bypassing `common` workflow
=> ci: Adds codecov.yaml file

component/storage/couchdb/go.mod, component/storage/couchdb/go.sum, component/storage/couchdb/store_test.go, component/storage/mysql/go.mod, component/storage/mysql/go.sum, component/storage/mysql/store_test.go
This PR adds common tests for storage package. Tests are covering CouchDB and MySQL implementation.
=> test: Adds common tests (couchdb, mysql)

.github/workflows/common.yml, .github/workflows/storage-couchdb.yml, .github/workflows/storage-mongodb.yml, .github/workflows/storage-mysql.yml, .gitignore, scripts/check_unit.sh
=> chore: Updates Codecov

component/storage/mysql/store.go, component/storage/mysql/store_test.go
=> refactor: MySQL uses now own errors

.github/workflows/vdr-sidetree.yml
=> chore: add vdr-sidetree workflow

component/newstorage/couchdb/store.go, component/newstorage/couchdb/store_internal_test.go, component/newstorage/couchdb/store_test.go, test/component/newstorage/newstore.go
=> feat: Query method for new CouchDB storage implementation

component/newstorage/couchdb/store.go, component/newstorage/couchdb/store_internal_test.go, component/newstorage/couchdb/store_test.go, test/component/newstorage/newstore.go
- Also includes a minor refactor for the getQueryOptions function that was added in my previous commit.
=> feat: GetBulk method for new CouchDB storage implementation

component/newstorage/couchdb/store.go, component/newstorage/couchdb/store_internal_test.go, component/newstorage/couchdb/store_test.go, test/component/newstorage/newstore.go
=> feat: Batch method for new CouchDB storage implementation

.codecov.yaml
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: remove project codecov status check

.codecov.yaml
Potential followup:
- https://docs.codecov.io/docs/commit-status#excluding-status-checks-for-unrelated-projects-example
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: prepare codecov settings split

component/vdr/sidetree/doc/doc.go
=> fix: GetPublicKeyJWK bug

component/vdr/sidetree/client.go, component/vdr/sidetree/client_test.go, component/vdr/sidetree/doc/doc.go, component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum, component/vdr/sidetree/option/create/option.go, component/vdr/sidetree/option/recovery/option.go, component/vdr/sidetree/option/update/option.go
=> chore: updare aries revision

component/vdr/sidetree/client.go, component/vdr/sidetree/client_test.go, component/vdr/sidetree/option/deactivate/option.go, component/vdr/sidetree/option/recovery/option.go, component/vdr/sidetree/option/update/option.go
=> chore: Add WithRecoveryCommitment and WithUpdateCommitment

component/vdr/trustbloc/vdr.go, component/vdr/trustbloc/vdr_test.go
=> chore: Support adding sidetree purposes

.github/workflows/repolint.yml, .repolint.json, CODE_OF_CONDUCT.md, CONTRIBUTING.md, MAINTAINERS.md, README.md, SECURITY.md
Signed-off-by: Troy Ronda <troy@troyronda.com>
=> chore: Add repolint

component/storage/couchdb/go.mod, component/storage/couchdb/store_test.go, component/storage/mysql/go.mod, component/storage/mysql/store_test.go
=> fix: CouchDB and MySQL storage Go module paths

component/storage/couchdb/go.mod, component/storage/couchdb/go.sum
=> chore: Updates aries revision

component/storage/mysql/store.go, component/storage/mysql/store_test.go
=> fix: MySQL provider "store not found" errors when prefix is used

component/storage/mysql/store.go
=> fix: MySQL not storing binary data correctly

component/storage/couchdb/store.go
- Also removed a TODO that was fixed previously.
- Created a new TODO to use attachments for binary data instead.
closes #78
=> fix: Binary data not storing correctly with CouchDB storage provider

component/storage/couchdb/store.go, component/storage/couchdb/store_internal_test.go, component/storage/couchdb/store_test.go
- Tags field is now nested, which prevents potential name conflicts.
- Refactored document storage code.
closes #65
=> feat: Improvements to CouchDB document storage

component/vdr/sidetree/client.go, component/vdr/sidetree/option/create/option.go, component/vdr/sidetree/option/recovery/option.go
=> feat: add AnchorOrigin to sidetree request (create,recover)

component/vdr/sidetree/client.go
=> fix: remove hardcoded operation in url

component/vdr/orb/config/service.go, component/vdr/orb/config/service_test.go, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go
-Lookup n from the https://trustbloc.dev/ns/min-resolvers property.
-Fetches the configurations at each chosen link using WebFinger.
-Validates that each well-known configuration has the same policy for n and that all of the chosen links are listed in the n fetched configurations.
-Resolve the DID at each of the n chosen links.
-Ensure that the DID resolution result matches (other than resolver-specific metadata such as timestamps).
-In case of a mismatch, additional links may need to be chosen until the client has n matches.
=> feat: add Shared Resolution Domain validation

component/vdr/orb/config/service.go
=> fix: send empty body for GET

component/storage/couchdb/store.go, component/storage/couchdb/store_internal_test.go, component/storage/couchdb/store_test.go
=> feat: Index creation retries and better logging

test/bdd/vdr/orb/create_follow_activity.sh, test/bdd/vdr/orb/features/orb_e2e.feature, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/fixtures/orb/mysql-config/mysql_config.sql, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: update to latest orb

component/vdr/orb/README.md, component/vdr/orb/config/service.go, component/vdr/orb/config/service_test.go, test/bdd/vdr/orb/create_follow_activity.sh, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: update to orb v0.1 

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> fix: get resolution endpoints from configure domain

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum, component/vdr/trustbloc/go.mod, component/vdr/trustbloc/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum, test/bdd/vdr/trustbloc/go.mod, test/bdd/vdr/trustbloc/go.sum
=> chore: update to latest aries

.gitignore, test/bdd/vdr/orb/create_follow_activity.sh, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: update orb revision

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum, component/vdr/trustbloc/go.mod, component/vdr/trustbloc/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum, test/bdd/vdr/trustbloc/go.mod, test/bdd/vdr/trustbloc/go.sum
=> chore: update afgo version

component/vdr/orb/README.md
=> fix: orb vdr docs

test/bdd/vdr/orb/create_follow_activity.sh, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: update to latest vct and orb

MAINTAINERS.md
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> chore: update active maintainer list

component/vdr/orb/config/service.go, component/vdr/orb/internal/ldcontext/data/anchor-v1.json, component/vdr/orb/internal/ldcontext/ldcontext.go, component/vdr/orb/internal/ldcontext/ldcontext_test.go, component/vdr/orb/vdr.go, test/bdd/vdr/orb/create_follow_activity.sh, test/bdd/vdr/orb/features/orb_e2e.feature, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/pkg/context/context.go, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> test: add test for did orb ipns

component/vdr/orb/config/service.go, component/vdr/orb/config/service_test.go, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/create_follow_activity.sh, test/bdd/vdr/orb/features/orb_e2e.feature, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> feat: get latest anchor origin

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/create_follow_activity.sh
=> feat: resolve webcas in orb vdr

component/vdr/orb/config/service.go, component/vdr/orb/config/service_test.go
=> chore: rename webfinger response struct

component/vdr/orb/config/service.go
=> fix: ipns config

test/bdd/vdr/orb/bddtests_test.go, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml
=> fix: Fixes bdd tests

component/storage/couchdb/go.mod, component/storage/couchdb/go.sum, component/storage/couchdb/store.go, component/storage/mongodb/go.mod, component/storage/mongodb/go.sum, component/storage/mysql/go.mod, component/storage/mysql/go.sum, component/storage/mysql/store.go, component/storage/mysql/store_test.go
=> chore: Update storage implementations to pass new common tests

component/vdr/indy/resolver.go
Signed-off-by: Ardian <ardianabazi09@gmail.com>
=> added nil check for nym reply

component/vdr/orb/vdr.go
=> chore: add timeout for http client

component/storage/mongodb/store.go
=> docs: Fix incorrect MongoDB provider documentation

component/vdr/sidetree/client_test.go, component/vdr/sidetree/doc/doc.go, component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum, test/bdd/vdr/orb/go.sum, test/bdd/vdr/trustbloc/go.sum
=> fix: allow creating/updating doc with base58 pub keys in vdr/sidetree

component/vdr/orb/go.mod, component/vdr/orb/go.sum, test/bdd/vdr/orb/go.mod
=> chore: update orb vdr to latest sidetree vdr

component/vdr/orb/go.mod, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go
=> fix: allow creating docs with base58 keys in orb vdr

component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
Reworked the MongoDB storage provider to use one client (and one connection) across stores. It's safe to reuse that client object and saves on extra unnecessary connections.
=> feat: Reuse MongoDB connection across stores

component/vdr/indy/creator.go, component/vdr/indy/creator_test.go, component/vdr/indy/go.mod, component/vdr/indy/go.sum, component/vdr/indy/resolver.go, component/vdr/indy/resolver_test.go, component/vdr/indy/vdr.go, component/vdr/indy/vdr_test.go
Suggestions and comments (including critiques) are more than welcomed. 
Signed-off-by: Ardian Abazi <ardianabazi09@gmail.com>
=> updated indy vdr component to be compliant with v0.1.6 aries

component/storage/mysql/store.go, component/storage/mysql/store_test.go
Increased from BLOB to MEDIUMBLOB.
=> feat: Increase max data size for MySQL storage provider

component/storage/mongodb/go.mod, component/storage/mongodb/go.sum, component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
=> fix: Retry on transient Put and Batch errors for MongoDB

Makefile, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/features/orb_e2e.feature, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> feat: resolve did from https hint

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: avoid adding current keys when update did

component/storage/mongodb/go.mod, component/storage/mongodb/go.sum, component/storage/mongodb/store.go
=> fix: Large integer storage not working correctly with MongoDB provider

component/storage/couchdb/go.mod, component/storage/couchdb/go.sum, component/storage/mongodb/go.mod, component/storage/mongodb/go.sum, component/storage/mysql/go.mod, component/storage/mysql/go.sum
=> chore: Update storage SPI and tests commit versions

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: Add commitment to KeyRetriever interface

component/vdr/orb/go.mod, component/vdr/orb/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: check for error did not found

component/vdr/orb/vdr.go, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> feat: allow vdr to accept did with verification methods

.github/workflows/vdr-orb.yml, component/vdr/orb/vdr.go, test/bdd/vdr/orb/features/orb_e2e.feature
=> feat: resolve hl cas links

component/storage/mongodb/go.mod, component/storage/mongodb/go.sum, component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
Also fixed an issue where querying for integer tags would result in no results being found.
=> feat: Support for querying for two tags at once with MongoDB

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/create_follow_activity.sh
=> feat: add UnanchoredMaxLifeTime option

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
=> fix: check TransactionTime in checkUnanchoredDIDTime

component/vdr/orb/vdr.go
=> fix: read unix time in utc

component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
To work around this issue, dots in field names will now get converted to backtick (`) characters when being stored, and converted back to dots upon retrieving. This has the consequence of making backticks reserved characters for field names, since if someone tries using one then that data will get incorrectly unescaped on retrieval. To prevent this situation, an error will now get returned if there's an attempt to store JSON data that uses backticks in field names.
Although this is a limitation of DocumentDB and not MongoDB, since this MongoDB storage provider can't reliably tell whether DocumentDB is being used or not, this dot replacement behaviour will also apply even if MongoDB is being used.
=> fix: Error when storing JSON to DocumentDB that use dots in field names

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go
=> feat: check max usage for cached update DID

component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
=> fix: Dots in nested array objects not escaping for DocumentDB

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/orb/tracing/prod.go, component/vdr/orb/tracing/test.go, component/vdr/orb/vdr.go, test/bdd/vdr/orb/go.sum
=> chore: add tracing for vdr read

component/vdr/orb/vdr.go
=> chore: configure http client in orb vdr

component/vdr/sidetree/client_test.go, component/vdr/sidetree/option.go
=> chore: add custom http client option

component/vdr/sidetree/client.go
=> fix: sidetree vdr

component/vdr/orb/go.mod, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: update http2 for http client

component/vdr/orb/go.mod, component/vdr/orb/go.sum, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/go.sum
=> chore: update orb to latest

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go
=> chore: remove check for published DID when update

component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go
=> fix: vdr resolve to work with http hint

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/orb/vdr.go, go.mod, test/bdd/vdr/orb/create_follow_activity.sh, test/bdd/vdr/orb/features/orb_e2e.feature, test/bdd/vdr/orb/fixtures/orb/.env, test/bdd/vdr/orb/fixtures/orb/docker-compose.yml, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> feat: add support to resolve with versionId or versionTime

component/vdr/sidetree/api/api.go, component/vdr/sidetree/client.go, component/vdr/sidetree/client_test.go, component/vdr/sidetree/option/deactivate/option.go, component/vdr/sidetree/option/recovery/option.go, component/vdr/sidetree/option/update/option.go, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum, test/bdd/vdr/trustbloc/go.mod, test/bdd/vdr/trustbloc/go.sum
=> fix: replace GetSigningKey with GetSigner

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum, test/bdd/vdr/orb/pkg/vdr/vdr_steps.go
=> chore: Replace GetSigningKey with GetSigner in orb VDR

component/storage/postgresql/go.mod, component/storage/postgresql/go.sum, component/storage/postgresql/store.go, component/storage/postgresql/store_test.go
Support for SetStoreConfig, Close and Query methods (with some limitations).
=> feat: PostgreSQL provider SetStoreConfig, Close and Query support

component/storage/postgresql/go.mod, component/storage/postgresql/store.go, component/storage/postgresql/store_test.go
=> fix: add dbname in right location in connect string

component/vdr/orb/go.mod, component/vdr/orb/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
=> chore: complete release for orb vdr

component/storage/postgresql/go.mod, component/storage/postgresql/store.go
=> fix: postgres default db

component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
Added a workaround for an issue where if you call OpenStore without having stored any data or created indexes, then the GetStoreConfig method will report ErrStoreNotFound. This is due to how MongoDB defers the creation of the underlying database until actual storage calls are made.
=> fix: MongoDB provider GetStoreConfig returning ErrStoreNotFound

component/storage/couchdb/store.go, component/storage/couchdb/store_test.go, component/storage/mongodb/store.go, component/storage/mongodb/store_test.go, component/storage/postgresql/store.go, component/storage/postgresql/store_test.go
=> feat: Ping methods for MongoDB, CouchDB, and PostgreSQL

component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
- For the Put and Batch method, updating an existing value that was of a different type (JSON, binary, or JSON string) would result in the existing data still being there in the data wrapper, which can cause storage bloat and retrieval issues. This was fixed by using the MongoDB Replace method instead of Update.
- For the PutAsJSON and BatchAsJSON methods, JSON tags in Go structs were being ignored by the MongoDB Go driver. This was fixed by preparing the data to be stored as a map (similar to how the current Put method works with JSON data).
=> fix: MongoDB update and PutAsJSON issues

component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
This will give the caller the ability to have more control over custom queries in MongoDB.
=> feat: Added find options to MongoDB CustomQuery method

component/vdr/sidetree/client.go, component/vdr/sidetree/client_test.go, component/vdr/sidetree/doc/doc.go, component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum
=> chore: update to latest aries for sidetree vdr

component/vdr/sidetree/doc/doc.go
=> fix: sidetree vdr serivce endpoint logic

component/vdr/sidetree/client_test.go, component/vdr/sidetree/doc/doc.go
=> fix: routing keys in vdr orb

component/vdr/orb/go.mod, component/vdr/orb/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
=> chore: update sidetree vdr in orb vdr

component/vdr/sidetree/doc/doc.go
=> chore: add accept to service request for orb vdr

component/vdr/orb/go.mod, component/vdr/orb/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
=> chore: update to latest sidetree vdr

component/storage/mongodb/store.go, component/storage/mongodb/store_test.go
* Removed the BatchAsJSON method since the new BulkWrite method introduced in the previous commit can do the same thing but with more flexibility
* Added a clarification on the PrepareDataForBSONStorage helper function (which is intended to be used with BulkWrite).
* BulKWrite now returns a more accurate error message if an InsertOne model is being used.
=> feat: Remove MongoDB BatchAsJSON method

component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum
=> chore: update sidetree-core-go in sidetree vdr

component/vdr/orb/util/concurrent/rollingcounter/rollingcounter.go
=> fix: switch from math/rand to crypto/rand

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
Update sidetree-core-go (alsoKnownAs)
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>
=> wip: Update sidetree-core-go (alsoKnownAs)

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/orb/vdr.go, component/vdr/orb/vdr_test.go, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
Add support for AlsoKnownAs to Orb VDR
Closes #274
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>
=> feat: Add support for AlsoKnownAs to Orb VDR

component/vdr/orb/go.mod, component/vdr/orb/go.sum, component/vdr/sidetree/go.mod, component/vdr/sidetree/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
Update sidetree-core and orb
Closes #277
Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>
=> chore: Update sidetree-core (rename also-known-as patches)

component/vdr/orb/go.mod, component/vdr/orb/go.sum, test/bdd/vdr/orb/go.mod, test/bdd/vdr/orb/go.sum
=> chore: update to latest sidetree revision

component/vdr/orb/vdr.go
=> feat: use different domain when anchor origin is down

component/vdr/sidetree/client.go, component/vdr/sidetree/client_test.go, component/vdr/sidetree/option.go
=> chore: Add auth token provider

README.md
Signed-off-by: Troy Ronda <troy.ronda@securekey.com>
=> docs: add afgo extension mention to readme
